name: ci

on:
  schedule:
    - cron: "59 */6 * * *"
  push:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pdftotext
        run: |
          python tests/unit/test_settings.py
